apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: rhd-tutorial-kn-deploy
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  params:
    - name: serviceName
      description: The name of the Knative service
    - name: applicationSrcDir
      description: The source directory of the application within the source repository
  tasks:
  - name: build
    taskRef:
      name: quarkus-native
    params:
      - name: tlsVerify
        value: "false"
      - name: contextDir
        value: "${params.applicationSrcDir}"
      # if you have different repository manager update the value below
      # if don't wish to use nexus or repo manager then comment the name/value below
      - name: mavenMirrorUrl
        value: 'http://nexus:8081/nexus/content/groups/public'
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image
  - name: deploy
    taskRef:
      name: kn-create-service
    runAfter:
      - build
    params:
      - name: name
        value: ${params.serviceName}
    resources:
      inputs:
      - name : image
        resource: app-image
      