apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: recommendation-ksvc-pipeline-
spec:
  pipelineRef:
    name: rhd-tutorial-kn-deploy
  params:
    - name: serviceName
      value: recommendation
    - name: applicationSrcDir
      value: recommendation
  trigger:
    type: manual
  serviceAccount: 'pipeline'
  resources:
  - name: app-git
    resourceRef:
      name: korea-keynote-demo-git
  - name: app-image
    resourceRef:
      name: recommendation-openshift-image-v2
