apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: recommendation-v2-pipeline-
spec:
  pipelineRef:
    name: rhd-tutorial-deploy
  params:
    - name: "deploymentConfig"
      value: "recommendation-v2"
    - name: "applicationSrcDir"
      value: "recommendation"
  trigger:
    type: manual
  serviceAccount: 'pipeline'
  resources:
  - name: app-git
    resourceRef:
      name: korea-keynote-demo-git-v2
  - name: app-image
    resourceRef:
      name: recommendation-openshift-image-v2