apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: recom-deploy-openshift-pipeline
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build
    taskRef:
      name: s2i-quarkus
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "recommendation/java/quarkus"
      # if you have different repository manager update the value below
      # if don't wish to use nexus or repo manager then comment the name/value below
      - name: MAVEN_MIRROR_URL
        value: 'http://nexus:8081/nexus/content/groups/public'
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image
  - name: deploy
    taskRef:
      name: openshift-client
    runAfter:
      - build
    params:
    - name: ARGS
      value: "rollout latest recommendation"