apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: customer-pipeline-
spec:
  pipelineRef:
    name: rhd-tutorial-deploy
  params:
    - name: deploymentConfig
      value: customer
    - name: applicationSrcDir
      value: customer
  serviceAccount: "pipeline"
  resources:
    - name: app-git
      resourceRef:
        name: korea-keynote-demo-git
    - name: app-image
      resourceRef:
        name: customer-openshift-image
